[package]
name = "igvm_svsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
igvm_defs = { path = '../ms_igvm/igvm_defs' }
igvm = { path = '../ms_igvm/igvm' }
